# Generated by Django 6.0.1 on 2026-07-20 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('telegram', models.CharField(blank=True, max_length=80)),
                ('currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], default='CHF', max_length=3)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(db_index=True, max_length=7, unique=True)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month_key'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=8, max_digits=6)),
                ('logistics_fixed_chf', models.DecimalField(decimal_places=2, default=2800, max_digits=12)),
                ('rate_chf_uah', models.DecimalField(decimal_places=4, default=47.2, max_digits=12)),
                ('rate_eur_uah', models.DecimalField(decimal_places=4, default=44.85, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('car', models.CharField(max_length=160)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('execution', models.CharField(choices=[('won', 'Виграно'), ('confirmed', 'Підтверджено'), ('picked', 'Забрано'), ('in_transit', 'В дорозі'), ('customs', 'Розмитнено'), ('delivered', 'Доставлено')], default='won', max_length=20)),
                ('payment', models.CharField(choices=[('unpaid', 'Не оплачено'), ('pending', 'Очікує'), ('partial', 'Частково'), ('paid', 'Оплачено'), ('waiting', 'Очікує'), ('debt', 'Борг')], default='unpaid', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('won_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], default='CHF', max_length=3)),
                ('won_currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], default='CHF', max_length=3)),
                ('bid_currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], default='CHF', max_length=3)),
                ('cost_currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], default='CHF', max_length=3)),
                ('price_currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], default='CHF', max_length=3)),
                ('delivery_currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], default='CHF', max_length=3)),
                ('vin', models.CharField(blank=True, max_length=64)),
                ('lot_url', models.URLField(blank=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('logistics', models.JSONField(blank=True, default=dict)),
                ('delivery_type', models.CharField(choices=[('pickup', 'Самовивіз'), ('theirs', 'Їх доставка'), ('ours', 'Наша доставка')], default='pickup', max_length=20)),
                ('auction', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('driver', models.CharField(max_length=120)),
                ('plate', models.CharField(blank=True, max_length=40)),
                ('route', models.CharField(blank=True, max_length=160)),
                ('cars', models.PositiveIntegerField(default=0)),
                ('departure', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Планування'), ('loading', 'Завантаження'), ('in_transit', 'В дорозі'), ('arrived', 'Прибув'), ('done', 'Завершено')], default='planning', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deals', models.ManyToManyField(blank=True, related_name='carriers', to='core.deal')),
            ],
            options={
                'ordering': ['-departure', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealDuePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('place', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_payments', to='core.deal')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.carrier')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.deal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('client_name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('criteria', models.TextField(blank=True)),
                ('manager', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('new', 'Новий'), ('searching', 'У пошуку'), ('review', 'Є кандидати'), ('agreed', 'Погоджено'), ('negotiating', 'Торгуємось'), ('won', 'Виграли'), ('lost', 'Не виграли'), ('closed', 'Закрито')], default='new', max_length=20)),
                ('candidates', models.PositiveIntegerField(default=0)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.deal')),
            ],
            options={
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], default='CHF', max_length=3)),
                ('place', models.CharField(blank=True, max_length=120)),
                ('paid_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.deal')),
            ],
            options={
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('won', 'Виграні'), ('confirmed', 'Підтверджені')], max_length=20)),
                ('car', models.CharField(max_length=160)),
                ('client', models.CharField(blank=True, max_length=160)),
                ('stage', models.CharField(blank=True, max_length=40)),
                ('won_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('delivery_type', models.CharField(choices=[('pickup', 'Самовивіз'), ('theirs', 'Їх доставка'), ('ours', 'Наша доставка')], default='pickup', max_length=20)),
                ('currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], default='CHF', max_length=3)),
                ('won_currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], default='CHF', max_length=3)),
                ('bid_currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], default='CHF', max_length=3)),
                ('cost_currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], default='CHF', max_length=3)),
                ('price_currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], default='CHF', max_length=3)),
                ('delivery_currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], default='CHF', max_length=3)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_rows', to='core.deal')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.reportmonth')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['month', 'report_type'], name='core_report_month_i_286183_idx')],
            },
        ),
    ]
