"""Mock-дані для UI-прототипу Autolot CRM."""

COCKPIT_STATS = [
    {"id": "receivable", "label": "До отримання", "value": "142 800", "currency": "CHF", "trend": "+12%", "up": True},
    {"id": "profit", "label": "Прибуток місяця", "value": "28 450", "currency": "CHF", "trend": "+8%", "up": True},
    {"id": "in_transit_money", "label": "Гроші в дорозі", "value": "67 200", "currency": "EUR", "trend": "-3%", "up": False},
    {"id": "cars_transit", "label": "Авто в дорозі", "value": "14", "currency": "шт", "trend": "+2", "up": True},
]

ACTION_QUEUES = [
    {"id": "confirm", "title": "Чекають підтвердження", "count": 5, "icon": "clock", "color": "amber"},
    {"id": "pickup", "title": "Готові до забору", "count": 3, "icon": "truck", "color": "cyan"},
    {"id": "customs", "title": "В дорозі / митниця", "count": 8, "icon": "route", "color": "blue"},
    {"id": "debt", "title": "Доставлено + борг", "count": 4, "icon": "wallet", "color": "red"},
    {"id": "no_vin", "title": "Без VIN / фото", "count": 2, "icon": "alert", "color": "orange"},
    {"id": "stuck", "title": "Застрягли", "count": 1, "icon": "pause", "color": "purple"},
]

DEALS = [
    {
        "id": "AL-2026-047",
        "car": "BMW X5 xDrive40d",
        "year": 2021,
        "client": "Олександр К.",
        "phone": "+380 67 123 4567",
        "execution": "in_transit",
        "execution_label": "В дорозі",
        "payment": "partial",
        "payment_label": "Частково",
        "price": 42500,
        "paid": 28000,
        "debt": 14500,
        "currency": "CHF",
        "profit": 3200,
        "vin": "WBA***847291",
        "lot_url": "https://auto-lot.com/lot/48291",
        "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400&h=260&fit=crop",
        "logistics": {"confirmed": "2026-05-03", "picked": "2026-05-12", "transit": "2026-05-18", "customs": None, "delivered": None},
        "delivery_type": "ours",
        "auction": "BCP",
        "won_price": 38200,
        "bid": 38000,
        "cost": 34850,
        "delivery_cost": 1800,
        "commission": 2100,
        "won_currency": "CHF",
        "bid_currency": "CHF",
        "cost_currency": "CHF",
        "price_currency": "CHF",
        "delivery_currency": "CHF",
        "due_payments": [
            {"id": "due-1", "amount": 1350, "place": "На офісі"},
            {"id": "due-2", "amount": 3900, "place": "Біля авто"},
        ],
        "documents": [
            {"id": "doc-1", "name": "Договір купівлі.pdf", "added": "2026-06-10"},
            {"id": "doc-2", "name": "VIN-фото.jpg", "added": "2026-06-12"},
        ],
        "notes": "Клієнт просив перевірити комплектацію M Sport. Очікуємо підтвердження після огляду фото.",
    },
    {
        "id": "AL-2026-046",
        "car": "Mercedes-Benz GLC 300",
        "year": 2020,
        "client": "Марина В.",
        "phone": "+380 50 987 6543",
        "execution": "customs",
        "execution_label": "Розмитнено",
        "payment": "paid",
        "payment_label": "Оплачено",
        "price": 38900,
        "paid": 38900,
        "debt": 0,
        "currency": "CHF",
        "profit": 4100,
        "vin": "WDC***102847",
        "lot_url": "https://auto-lot.com/lot/48102",
        "image": "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=400&h=260&fit=crop",
        "logistics": {"confirmed": "2026-04-20", "picked": "2026-04-28", "transit": "2026-05-05", "customs": "2026-06-10", "delivered": None},
        "delivery_type": "theirs",
        "auction": "SCC",
        "won_price": 34100,
        "bid": 33800,
        "cost": 31898,
        "delivery_cost": 0,
        "commission": 1900,
        "won_currency": "CHF",
        "bid_currency": "CHF",
        "cost_currency": "CHF",
        "price_currency": "CHF",
        "delivery_currency": "CHF",
    },
    {
        "id": "AL-2026-045",
        "car": "Audi Q7 55 TFSI",
        "year": 2019,
        "client": "Дмитро П.",
        "phone": "+380 63 555 1234",
        "execution": "confirmed",
        "execution_label": "Підтверджено",
        "payment": "pending",
        "payment_label": "Очікує",
        "price": 51200,
        "paid": 15000,
        "debt": 36200,
        "currency": "EUR",
        "profit": 5800,
        "vin": "",
        "lot_url": "https://auto-lot.com/lot/47955",
        "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400&h=260&fit=crop",
        "logistics": {"confirmed": "2026-06-28", "picked": None, "transit": None, "customs": None, "delivered": None},
        "delivery_type": "ours",
        "auction": "ALLIANZ",
        "won_price": 44100,
        "bid": 44000,
        "cost": 45400,
        "delivery_cost": 2200,
        "commission": 2800,
        "won_currency": "EUR",
        "bid_currency": "EUR",
        "cost_currency": "EUR",
        "price_currency": "EUR",
        "delivery_currency": "EUR",
    },
    {
        "id": "AL-2026-044",
        "car": "Volkswagen Tiguan R-Line",
        "year": 2022,
        "client": "Ірина С.",
        "phone": "+380 97 333 8899",
        "execution": "delivered",
        "execution_label": "Доставлено",
        "payment": "debt",
        "payment_label": "Борг",
        "price": 29800,
        "paid": 22000,
        "debt": 7800,
        "currency": "CHF",
        "profit": 2900,
        "vin": "WVG***556712",
        "lot_url": "https://auto-lot.com/lot/47844",
        "image": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=400&h=260&fit=crop",
        "logistics": {"confirmed": "2026-03-05", "picked": "2026-03-15", "transit": "2026-03-22", "customs": "2026-04-01", "delivered": "2026-04-18"},
        "delivery_type": "pickup",
        "auction": "REST",
        "won_price": 24200,
        "bid": 24000,
        "cost": 24436,
        "delivery_cost": 0,
        "commission": 1400,
        "won_currency": "CHF",
        "bid_currency": "CHF",
        "cost_currency": "CHF",
        "price_currency": "CHF",
        "delivery_currency": "CHF",
    },
    {
        "id": "AL-2026-043",
        "car": "Porsche Cayenne S",
        "year": 2021,
        "client": "Андрій М.",
        "phone": "+380 68 777 2211",
        "execution": "picked",
        "execution_label": "Забрано",
        "payment": "partial",
        "payment_label": "Частково",
        "price": 78500,
        "paid": 50000,
        "debt": 28500,
        "currency": "CHF",
        "profit": 9200,
        "vin": "WP1***334891",
        "lot_url": "https://auto-lot.com/lot/47743",
        "image": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400&h=260&fit=crop",
        "logistics": {"confirmed": "2026-05-25", "picked": "2026-06-01", "transit": None, "customs": None, "delivered": None},
        "delivery_type": "ours",
        "auction": "BCP",
        "won_price": 67500,
        "bid": 67000,
        "cost": 69300,
        "delivery_cost": 2400,
        "commission": 4200,
        "won_currency": "CHF",
        "bid_currency": "CHF",
        "cost_currency": "CHF",
        "price_currency": "CHF",
        "delivery_currency": "CHF",
    },
    {
        "id": "AL-2026-042",
        "car": "Toyota RAV4 Hybrid",
        "year": 2023,
        "client": "Віктор Л.",
        "phone": "+380 66 444 7788",
        "execution": "in_transit",
        "execution_label": "В дорозі",
        "payment": "paid",
        "payment_label": "Оплачено",
        "price": 33400,
        "paid": 33400,
        "debt": 0,
        "currency": "EUR",
        "profit": 3100,
        "vin": "JTM***992847",
        "lot_url": "https://auto-lot.com/lot/47642",
        "image": "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=400&h=260&fit=crop",
        "logistics": {"confirmed": "2026-05-15", "picked": "2026-05-20", "transit": "2026-05-25", "customs": None, "delivered": None},
        "delivery_type": "theirs",
        "auction": "SCC",
        "won_price": 28900,
        "bid": 28700,
        "cost": 27388,
        "delivery_cost": 0,
        "commission": 1700,
        "won_currency": "EUR",
        "bid_currency": "EUR",
        "cost_currency": "EUR",
        "price_currency": "EUR",
        "delivery_currency": "EUR",
    },
]

CLIENTS = [
    {"name": "Олександр К.", "phone": "+380 67 123 4567", "telegram": "@oleks_k", "deals": 3, "debt": 14500, "currency": "CHF"},
    {"name": "Марина В.", "phone": "+380 50 987 6543", "telegram": "@marina_v", "deals": 2, "debt": 0, "currency": "CHF"},
    {"name": "Дмитро П.", "phone": "+380 63 555 1234", "telegram": "", "deals": 1, "debt": 36200, "currency": "EUR"},
    {"name": "Ірина С.", "phone": "+380 97 333 8899", "telegram": "@ira_s", "deals": 4, "debt": 7800, "currency": "CHF"},
]

LEAD_STATUSES = [
    {"key": "new", "label": "Новий", "short": "Новий"},
    {"key": "searching", "label": "У пошуку", "short": "Пошук"},
    {"key": "review", "label": "Є кандидати", "short": "Кандидати"},
    {"key": "agreed", "label": "Погоджено", "short": "Погоджено"},
    {"key": "negotiating", "label": "Торгуємось", "short": "Торги"},
    {"key": "won", "label": "Виграли", "short": "Виграли"},
    {"key": "lost", "label": "Не виграли", "short": "Не виграли"},
    {"key": "closed", "label": "Закрито", "short": "Закрито"},
]

LEADS = [
    {
        "id": "RQ-021",
        "client": "Олег Ф.",
        "phone": "+380 96 555 1122",
        "date": "2026-06-22",
        "criteria": "Volvo XC90, 2020+, до 50k CHF",
        "manager": "Тимофій",
        "status": "new",
        "status_label": "Новий",
        "candidates": 0,
    },
    {
        "id": "RQ-020",
        "client": "Катерина Л.",
        "phone": "+380 63 777 8899",
        "date": "2026-06-21",
        "criteria": "Porsche Macan, бюджет до 55k EUR",
        "manager": "Тимофій",
        "status": "new",
        "status_label": "Новий",
        "candidates": 0,
    },
    {
        "id": "RQ-018",
        "client": "Петро Г.",
        "phone": "+380 93 111 2233",
        "date": "2026-06-20",
        "criteria": "BMW X3/X5, 2019+, бюджет 35–45k CHF",
        "manager": "Тимофій",
        "status": "searching",
        "status_label": "У пошуку",
        "candidates": 2,
    },
    {
        "id": "RQ-019",
        "client": "Вадим К.",
        "phone": "+380 50 333 4455",
        "date": "2026-06-19",
        "criteria": "Toyota Land Cruiser, дизель, до 60k CHF",
        "manager": "Тимофій",
        "status": "searching",
        "status_label": "У пошуку",
        "candidates": 3,
    },
    {
        "id": "RQ-017",
        "client": "Наталія Б.",
        "phone": "+380 67 888 9900",
        "date": "2026-06-18",
        "criteria": "Mercedes GLC, до 40k EUR, пробіг <80k",
        "manager": "Тимофій",
        "status": "review",
        "status_label": "Є кандидати",
        "candidates": 4,
    },
    {
        "id": "RQ-015",
        "client": "Юлія М.",
        "phone": "+380 97 222 3344",
        "date": "2026-06-14",
        "criteria": "Audi Q5, 2021+, quattro",
        "manager": "Тимофій",
        "status": "agreed",
        "status_label": "Погоджено",
        "candidates": 2,
    },
    {
        "id": "RQ-016",
        "client": "Сергій Т.",
        "phone": "+380 50 222 3344",
        "date": "2026-06-15",
        "criteria": "Audi A6 Avant, 2020+, дизель",
        "manager": "Тимофій",
        "status": "negotiating",
        "status_label": "Торгуємось",
        "candidates": 1,
    },
    {
        "id": "RQ-014",
        "client": "Артем Ш.",
        "phone": "+380 68 111 9988",
        "date": "2026-06-08",
        "criteria": "BMW 530d Touring, 2019+",
        "manager": "Тимофій",
        "status": "won",
        "status_label": "Виграли",
        "candidates": 1,
        "deal_id": "AL-2026-047",
    },
    {
        "id": "RQ-013",
        "client": "Леонід Д.",
        "phone": "+380 66 444 5566",
        "date": "2026-06-05",
        "criteria": "Range Rover Sport, до 70k CHF",
        "manager": "Тимофій",
        "status": "lost",
        "status_label": "Не виграли",
        "candidates": 3,
    },
    {
        "id": "RQ-012",
        "client": "Гanna P.",
        "phone": "+380 93 888 7766",
        "date": "2026-05-28",
        "criteria": "VW Passat B8, універсал",
        "manager": "Тимофій",
        "status": "closed",
        "status_label": "Закрито",
        "candidates": 0,
    },
]

CARRIERS = [
    {
        "id": "TR-012",
        "route": "Цюрих → Львів",
        "status": "in_transit",
        "status_label": "В дорозі",
        "cars": 6,
        "departure": "2026-06-10",
        "eta": "2026-06-22",
        "driver": "Михайло Коваль",
        "plate": "CH-ZH 4821",
        "assigned_deals": ["AL-2026-047", "AL-2026-043"],
    },
    {
        "id": "TR-011",
        "route": "Берн → Київ",
        "status": "loading",
        "status_label": "Завантаження",
        "cars": 4,
        "departure": "2026-06-24",
        "eta": "2026-07-05",
        "driver": "Василь Петренко",
        "plate": "CH-BE 3109",
        "assigned_deals": ["AL-2026-045", "AL-2026-042"],
    },
]

MONTHLY_REPORTS = {
    "2026-06": {
        "month": "Червень 2026",
        "month_key": "2026-06",
        "deal_count": 32,
        "sections": [
            {"name": "У роботі", "count": 18, "cost": 412000, "revenue": 498000, "paid": 320000, "debt": 178000, "profit": 86000},
            {"name": "Доставлені", "count": 9, "cost": 198000, "revenue": 245000, "paid": 231000, "debt": 14000, "profit": 47000},
            {"name": "Скасовані", "count": 2, "cost": 0, "revenue": 0, "paid": 0, "debt": 0, "profit": 0},
        ],
    },
    "2026-05": {
        "month": "Травень 2026",
        "month_key": "2026-05",
        "deal_count": 28,
        "sections": [
            {"name": "У роботі", "count": 15, "cost": 365000, "revenue": 441000, "paid": 290000, "debt": 151000, "profit": 76000},
            {"name": "Доставлені", "count": 11, "cost": 241000, "revenue": 297000, "paid": 285000, "debt": 12000, "profit": 56000},
            {"name": "Скасовані", "count": 2, "cost": 0, "revenue": 0, "paid": 0, "debt": 0, "profit": 0},
        ],
    },
    "2026-04": {
        "month": "Квітень 2026",
        "month_key": "2026-04",
        "deal_count": 25,
        "sections": [
            {"name": "У роботі", "count": 12, "cost": 312000, "revenue": 378000, "paid": 251000, "debt": 127000, "profit": 66000},
            {"name": "Доставлені", "count": 10, "cost": 218000, "revenue": 269000, "paid": 261000, "debt": 8000, "profit": 51000},
            {"name": "Скасовані", "count": 3, "cost": 0, "revenue": 0, "paid": 0, "debt": 0, "profit": 0},
        ],
    },
}

MONTHLY_REPORT = MONTHLY_REPORTS["2026-06"]

REPORT_SECTIONS = [
    {
        "name": "У роботі",
        "rows": [
            {"car": "SEAT Ibiza 1.2 TSI", "client": "Сергій Шевчук", "stage": "Виграно", "won_price": 14800, "bid": 14600, "cost": 16980, "price": 20700, "delivery_cost": 950, "profit": 3720, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "ours"},
            {"car": "Tesla Model S 85 Performance D", "client": "Влад Олексюк", "stage": "В дорозі", "won_price": 25800, "bid": 25600, "cost": 28354, "price": 34540, "delivery_cost": 1400, "profit": 6186, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "ours"},
            {"car": "BMW X5 xDrive30d", "client": "Микита Горишній", "stage": "Підтверджено", "won_price": 30200, "bid": 30000, "cost": 33590, "price": 39291, "delivery_cost": 1800, "profit": 5700, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "ours", "deal_id": "AL-2026-047"},
            {"car": "Audi A6 3.0 TDI quattro", "client": "Денис Запорожець", "stage": "Забрано", "won_price": 25900, "bid": 25700, "cost": 28700, "price": 35000, "delivery_cost": 0, "profit": 6300, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "theirs"},
            {"car": "Mercedes-AMG GLC 63 4MATIC", "client": "Олег Кравчук", "stage": "Розмитнено", "won_price": 41500, "bid": 41200, "cost": 45820, "price": 54800, "delivery_cost": 2100, "profit": 8980, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "ours"},
            {"car": "VW Golf 7 GTI 2.0 TSI", "client": "Ігор Мельник", "stage": "Виграно", "won_price": 10900, "bid": 10800, "cost": 12200, "price": 14900, "delivery_cost": 750, "profit": 2700, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "ours"},
            {"car": "Skoda Octavia RS 2.0 TSI", "client": "Павло Руденко", "stage": "В дорозі", "won_price": 13800, "bid": 13600, "cost": 15400, "price": 18800, "delivery_cost": 0, "profit": 3400, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "theirs"},
            {"car": "Ford Kuga 2.0 EcoBoost", "client": "Юрій Савченко", "stage": "Забрано", "won_price": 9800, "bid": 9700, "cost": 11200, "price": 13600, "delivery_cost": 900, "profit": 2400, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "ours"},
            {"car": "Porsche Macan S", "client": "Артем Бойко", "stage": "Підтверджено", "won_price": 33200, "bid": 33000, "cost": 36800, "price": 44200, "delivery_cost": 1900, "profit": 7400, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "ours"},
            {"car": "Volvo XC60 D5 AWD", "client": "Максим Ткаченко", "stage": "Розмитнено", "won_price": 19800, "bid": 19600, "cost": 22100, "price": 26800, "delivery_cost": 0, "profit": 4700, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "theirs"},
            {"car": "Hyundai Tucson 1.6 T-GDI", "client": "Роман Гнатюк", "stage": "Виграно", "won_price": 8700, "bid": 8600, "cost": 9800, "price": 11900, "delivery_cost": 800, "profit": 2100, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "ours"},
            {"car": "Mazda CX-5 2.5 AWD", "client": "Степан Литвин", "stage": "В дорозі", "won_price": 12800, "bid": 12600, "cost": 14300, "price": 17400, "delivery_cost": 0, "profit": 3100, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "theirs"},
        ],
    },
    {
        "name": "Доставлені",
        "rows": [
            {"car": "Volkswagen Tiguan R-Line", "client": "Ірина С.", "stage": "Доставлено", "won_price": 21800, "bid": 21600, "cost": 24436, "price": 29800, "delivery_cost": 0, "profit": 5364, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "pickup", "deal_id": "AL-2026-044"},
            {"car": "Mercedes-Benz GLC 300", "client": "Марина В.", "stage": "Доставлено", "won_price": 29600, "bid": 29400, "cost": 31898, "price": 38900, "delivery_cost": 0, "profit": 7002, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "theirs", "deal_id": "AL-2026-046"},
            {"car": "Toyota RAV4 Hybrid", "client": "Віктор Л.", "stage": "Доставлено", "won_price": 24800, "bid": 24600, "cost": 27388, "price": 33400, "delivery_cost": 0, "profit": 6012, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "theirs"},
            {"car": "BMW 320d xDrive Touring", "client": "Оксана М.", "stage": "Доставлено", "won_price": 11500, "bid": 11400, "cost": 13100, "price": 16200, "delivery_cost": 950, "profit": 3100, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "ours"},
            {"car": "Audi Q3 35 TFSI", "client": "Тарас Ж.", "stage": "Доставлено", "won_price": 16900, "bid": 16700, "cost": 18900, "price": 23100, "delivery_cost": 1100, "profit": 4200, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "ours"},
            {"car": "Peugeot 3008 GT Line", "client": "Лілія К.", "stage": "Доставлено", "won_price": 13900, "bid": 13700, "cost": 15600, "price": 19100, "delivery_cost": 0, "profit": 3500, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "theirs"},
        ],
    },
    {
        "name": "Скасовані",
        "rows": [
            {"car": "Opel Astra 1.4 Turbo", "client": "Богдан Ч.", "stage": "Скасовано", "won_price": 0, "bid": 0, "cost": 0, "price": 0, "delivery_cost": 0, "profit": 0, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "pickup"},
            {"car": "Renault Megane GT", "client": "Костянтин Я.", "stage": "Скасовано", "won_price": 0, "bid": 0, "cost": 0, "price": 0, "delivery_cost": 0, "profit": 0, "currency": "CHF", "won_currency": "CHF", "bid_currency": "CHF", "cost_currency": "CHF", "price_currency": "CHF", "delivery_currency": "CHF", "delivery_type": "pickup"},
        ],
    },
]

EXECUTION_STAGES = [
    {"key": "won", "label": "Виграно"},
    {"key": "confirmed", "label": "Підтверджено"},
    {"key": "picked", "label": "Забрано"},
    {"key": "in_transit", "label": "В дорозі"},
    {"key": "customs", "label": "Розмитнено"},
    {"key": "delivered", "label": "Доставлено"},
]

PAYMENTS_SAMPLE = [
    {"date": "2026-05-10", "amount": 15000, "currency": "CHF", "place": "На офісі"},
    {"date": "2026-05-28", "amount": 13000, "currency": "CHF", "place": "На місці"},
]

PRICE_BREAKDOWN = [
    {"label": "Виграш", "amount": 36500},
    {"label": "Комісія", "amount": 2920},
    {"label": "Логістика", "amount": 3080},
    {"label": "Коригування", "amount": 0},
]
