from django.urls import path

from . import api, api_2, views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('healthz/', api_2.healthz, name='healthz'),
    path('cockpit/', views.cockpit_view, name='cockpit'),
    path('deals/', views.deals_view, name='deals'),
    path('deals/<str:deal_id>/', views.deal_detail_view, name='deal_detail'),
    path('reports/', views.reports_redirect_view, name='reports'),
    path('reports/won/', views.reports_won_view, name='reports_won'),
    path('reports/confirmed/', views.reports_confirmed_view, name='reports_confirmed'),
    path('reports/archive/', views.reports_archive_list_view, name='reports_archive'),
    path(
        'reports/archive/<str:month_key>/',
        views.reports_archive_month_view,
        name='reports_archive_month',
    ),
    path('clients/', views.clients_view, name='clients'),
    path('leads/', views.leads_view, name='leads'),
    path('carriers/', views.carriers_view, name='carriers'),
    path('carriers/<str:carrier_id>/', views.carrier_detail_view, name='carrier_detail'),
    path('money/', views.money_view, name='money'),
    path('settings/', views.settings_view, name='settings'),
    path('media/<path:path>', api_2.media_serve, name='media_serve'),
    path('api/fetch-lot-photo/', views.fetch_lot_photo_view, name='fetch_lot_photo'),
    path('api/clients/', api.clients_collection, name='api_clients'),
    path('api/clients/<int:pk>/', api.client_detail, name='api_client_detail'),
    path('api/deals/', api.deals_collection, name='api_deals'),
    path('api/deals/<str:code>/', api.deal_detail, name='api_deal_detail'),
    path(
        'api/deals/<str:code>/due-payments/',
        api.deal_due_payments,
        name='api_deal_due_payments',
    ),
    path(
        'api/deals/<str:code>/documents/',
        api.deal_documents,
        name='api_deal_documents',
    ),
    path('api/documents/<int:pk>/', api.document_delete, name='api_document_delete'),
    path('api/leads/', api.leads_collection, name='api_leads'),
    path('api/leads/<str:code>/', api.lead_detail, name='api_lead_detail'),
    path('api/carriers/', api_2.carriers_collection, name='api_carriers'),
    path('api/carriers/<str:code>/', api_2.carrier_detail, name='api_carrier_detail'),
    path(
        'api/carriers/<str:code>/documents/',
        api_2.carrier_documents,
        name='api_carrier_documents',
    ),
    path('api/payments/', api_2.payments_collection, name='api_payments'),
    path('api/reports/rows/', api_2.reports_rows, name='api_reports_rows'),
    path('api/reports/rows/add/', api_2.reports_add_row, name='api_reports_add'),
    path('api/reports/rows/<int:pk>/', api_2.report_row_detail, name='api_report_row'),
    path('api/reports/rollover/', api_2.reports_rollover, name='api_reports_rollover'),
    path('api/reports/archive/', api_2.reports_archive_list, name='api_reports_archive'),
    path('api/settings/', api_2.settings_view, name='api_settings'),
]
